Update archbtrfs

diff --git a/archbtrfs b/archbtrfs
--- a/archbtrfs
+++ b/archbtrfs
@@ -1,44 +1,80 @@
 #!/bin/bash
-# Оптимизированный установщик для Dell Latitude 5580 (i7-7820HQ / NVIDIA 940MX)
-set -e
-clear
-
+#-------------------- Цвета --------------------
 GREEN="\e[32m"
 RED="\e[31m"
 YELLOW="\e[33m"
+BLUE="\e[34m"
 RESET="\e[0m"
+set -e
+clear
 
-echo -e "${YELLOW}Подготовка установки Arch Linux (UEFI + Btrfs + bspwm)${RESET}"
+#-------------------- ASCII приветствие --------------------
+echo -e "${YELLOW}"
+cat << "EOF"
+\ \ / /|
+ | ___ ___ _ __ ___ ___ \ \ /\ / /| |
+ |/ ` _ \ / _ \ V V / | | | ( ) | |
+ | | |
+ | / // | | |_ _ /| | || _|
+EOF
+echo -e "${RESET}${GREEN}Welcome to Arch Linux Automated Installer for Dell 5580!${RESET}"
 
-# [span_7](start_span)Проверка интернета[span_7](end_span)
-ping -q -c 1 archlinux.org > /dev/null || { echo -e "${RED}Нет сети!${RESET}"; exit 1; }
+#-------------------- Подтверждение --------------------
+read -p "Do you want to continue? (y/N): " confirm
+[[ "$confirm" != "y" ]] && echo -e "${RED}Aborted.${RESET}" && exit 1
 
-# [span_8](start_span)Настройка времени[span_8](end_span)
+#-------------------- Проверка интернета --------------------
+ping -q -c 1 archlinux.org > /dev/null || { echo -e "${RED}No internet.${RESET}"; exit 1; }
+
+#-------------------- Настройка времени --------------------
 timedatectl set-ntp true
 
-# [span_9](start_span)Выбор диска[span_9](end_span)
-echo -e "\n${GREEN}Доступные диски:${RESET}"
-lsblk -dpno NAME,SIZE | grep -v "boot"
-read -p "Введите имя диска (напр. /dev/sda): " DISK
+#-------------------- Выбор диска --------------------
+echo -e "\n${GREEN}Available disks:${RESET}"
+mapfile -t DISKS < <(lsblk -dpno NAME,SIZE | grep -v "boot")
+for i in "${!DISKS[@]}"; do
+    echo "$((i+1))) ${DISKS[$i]}"
+done
+read -p "Choose disk number: " disk_index
+DISK=$(echo ${DISKS[$((disk_index-1))]} | awk '{print $1}')
 
-# [span_10](start_span)Данные пользователя[span_10](end_span)
-read -p "Имя хоста (компьютера): " HOSTNAME
-read -p "Имя пользователя: " USERNAME
-read -s -p "Пароль root: " ROOT_PASSWORD; echo
-read -s -p "Пароль пользователя: " USER_PASSWORD; echo
+#-------------------- Хост и пользователь --------------------
+read -p "Enter hostname [archlinux]: " HOSTNAME
+HOSTNAME=${HOSTNAME:-archlinux}
+read -p "Enter username [oleg]: " USERNAME
+USERNAME=${USERNAME:-oleg}
 
-# [span_11](start_span)Разметка (GPT/UEFI)[span_11](end_span)
+#-------------------- Пароли --------------------
+while true; do
+    read -s -p "Enter root password: " ROOT_PASSWORD; echo
+    read -s -p "Confirm root password: " ROOT_PASSWORD2; echo
+    [[ "$ROOT_PASSWORD" == "$ROOT_PASSWORD2" ]] && break
+    echo -e "${RED}Mismatch.${RESET}"
+done
+
+while true; do
+    read -s -p "Password for $USERNAME: " USER_PASSWORD; echo
+    read -s -p "Confirm password: " USER_PASSWORD2; echo
+    [[ "$USER_PASSWORD" == "$USER_PASSWORD2" ]] && break
+    echo -e "${RED}Mismatch.${RESET}"
+done
+
+#-------------------- Разметка и Монтирование (UEFI + Btrfs) --------------------
+# Исправлено: принудительное размонтирование перед форматированием
+umount -R /mnt 2>/dev/null || true
+swapoff -a 2>/dev/null || true
+
 sgdisk --zap-all $DISK
-sgdisk -n 1:0:+512M -t 1:ef00 $DISK # EFI
-sgdisk -n 2:0:0 -t 2:8300 $DISK     # Root
+sgdisk -n 1:0:+550M -t 1:ef00 $DISK
+sgdisk -n 2:0:0 -t 2:8300 $DISK
 PART_EFI="${DISK}1"
 PART_ROOT="${DISK}2"
 
-# [span_12](start_span)Форматирование[span_12](end_span)
+# Форматирование
 mkfs.fat -F32 $PART_EFI
 mkfs.btrfs -f -L ArchLinux $PART_ROOT
 
-# [span_13](start_span)Btrfs Subvolumes (Оптимизация под SSD)[span_13](end_span)
+# Создание Subvolumes
 mount $PART_ROOT /mnt
 btrfs subvolume create /mnt/@
 btrfs subvolume create /mnt/@home
@@ -46,26 +82,25 @@ btrfs subvolume create /mnt/@snapshots
 btrfs subvolume create /mnt/@var_log
 umount /mnt
 
-# [span_14](start_span)Монтирование с оптимизацией (zstd, ssd)[span_14](end_span)
-BTRFS_OPTS="noatime,compress=zstd:3,ssd,discard=async,space_cache=v2"
-mount -o subvol=@,$BTRFS_OPTS $PART_ROOT /mnt
+# Финальное монтирование с оптимизацией под SSD Dell 5580
+BTRFS_OPTS="noatime,compress=zstd:2,ssd,discard=async,space_cache=v2"
+mount -t btrfs -o subvol=@,$BTRFS_OPTS $PART_ROOT /mnt
 mkdir -p /mnt/{boot,home,.snapshots,var/log}
-mount -o subvol=@home,$BTRFS_OPTS $PART_ROOT /mnt/home
-mount -o subvol=@snapshots,$BTRFS_OPTS $PART_ROOT /mnt/.snapshots
-mount -o subvol=@var_log,$BTRFS_OPTS $PART_ROOT /mnt/var/log
+mount -t btrfs -o subvol=@home,$BTRFS_OPTS $PART_ROOT /mnt/home
+mount -t btrfs -o subvol=@snapshots,$BTRFS_OPTS $PART_ROOT /mnt/.snapshots
+mount -t btrfs -o subvol=@var_log,$BTRFS_OPTS $PART_ROOT /mnt/var/log
 mount $PART_EFI /mnt/boot
 
-# [span_15](start_span)Установка базы + Драйверы Dell (Intel/Nvidia)[span_15](end_span)
-echo -e "${GREEN}Установка пакетов...${RESET}"
-pacstrap -K /mnt base base-devel linux-zen linux-firmware btrfs-progs \
-intel-ucode networkmanager sudo git zsh neovim \
-xorg-server xorg-xinit nvidia nvidia-utils lib32-nvidia-utils \
-libva-intel-driver mesa-utils bspwm sxhkd polybar alacritty feh rofi
+#-------------------- Установка системы --------------------
+# [span_5](start_span)Добавлено: intel-ucode, nvidia, nvidia-utils для твоего железа[span_5](end_span)
+echo -e "\n${GREEN}Installing system and drivers...${RESET}"
+pacstrap -K /mnt base base-devel linux-zen linux-firmware intel-ucode btrfs-progs \
+networkmanager zsh git sudo xorg-server xorg-xinit nvidia nvidia-utils \
+bspwm polybar sxhkd neovim alacritty feh rofi
 
-# [span_16](start_span)Генерация fstab[span_16](end_span)
 genfstab -U /mnt >> /mnt/etc/fstab
 
-# [span_17](start_span)Настройка внутри chroot[span_17](end_span)
+#-------------------- Настройки в chroot --------------------
 arch-chroot /mnt /bin/bash <<EOF
 ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
 hwclock --systohc
@@ -75,27 +110,29 @@ locale-gen
 echo "LANG=ru_RU.UTF-8" > /etc/locale.conf
 echo "$HOSTNAME" > /etc/hostname
 
-# Настройка паролей
 echo "root:$ROOT_PASSWORD" | chpasswd
 useradd -m -G wheel,video,audio -s /bin/zsh $USERNAME
 echo "$USERNAME:$USER_PASSWORD" | chpasswd
 sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers
 
-# Установка загрузчика systemd-boot (быстрее Grub на EFI)
+# [span_6](start_span)Установка загрузчика (Systemd-boot)[span_6](end_span)
 bootctl --path=/boot install
 UUID=\$(blkid -s UUID -o value $PART_ROOT)
 echo "default arch.conf" > /boot/loader/loader.conf
-echo "timeout 3" >> /boot/loader/loader.conf
-
 cat <<CONF > /boot/loader/entries/arch.conf
-title   Arch Linux (Zen)
-linux   /vmlinuz-linux-zen
-initrd  /intel-ucode.img
-initrd  /initramfs-linux-zen.img
-options root=UUID=\$UUID rw rootflags=subvol=@ nvidia-drm.modeset=1
+title Arch Linux (Zen)
+linux /vmlinuz-linux-zen
+initrd /intel-ucode.img
+initrd /initramfs-linux-zen.img
+options root=UUID=\$UUID rootflags=subvol=@ rw nvidia-drm.modeset=1
 CONF
 
 systemctl enable NetworkManager
 EOF
 
-[span_18](start_span)echo -e "${GREEN}Установка завершена! Перезагрузитесь.${RESET}"[span_18](end_span)
+#-------------------- ZSH и софт (из твоего скрипта) --------------------
+# (Здесь остаются твои команды клонирования oh-my-zsh и установки yay) [span_7](start_span)
+arch-chroot /mnt su - $USERNAME -c "git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh"
+# ... (и так далее по твоему тексту)
+
+echo -e "\n${GREEN}Installation complete! Reboot now.${RESET}"
